services:
  - type: web
    name: saineclothing-backend
    env: node
    buildCommand: "cd backend && npm install"
    startCommand: "cd backend && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: your-mongodb-uri
      - key: CLOUDINARY_URL
        value: your-cloudinary-url